import { Property, Region } from './types';

export const MOCK_REGIONS: Region[] = [
  // Active Countries
  { id: 'c-idn', parent_id: null, name: 'Indonesia', type: 'PROVINSI', country_code: 'IDN' },

  // Active Provinces (Indonesia)
  { id: 'p-jabar', parent_id: 'c-idn', name: 'Jawa Barat', type: 'PROVINSI', country_code: 'IDN' },

  // Active Cities (Jawa Barat)
  { id: 'city-tasik-kota', parent_id: 'p-jabar', name: 'Tasikmalaya', type: 'KOTA', country_code: 'IDN', lat: -7.3274, lng: 108.2207 },
  { id: 'city-tasik-kab', parent_id: 'p-jabar', name: 'Tasikmalaya', type: 'KABUPATEN', country_code: 'IDN', lat: -7.3500, lng: 108.1000 },

  // Active Kecamatans in Kota Tasikmalaya
  { id: 'kec-cibeureum', parent_id: 'city-tasik-kota', name: 'Cibeureum', type: 'KECAMATAN', country_code: 'IDN', lat: -7.3450, lng: 108.2450 },
  { id: 'kec-cihideung', parent_id: 'city-tasik-kota', name: 'Cihideung', type: 'KECAMATAN', country_code: 'IDN', lat: -7.3320, lng: 108.2180 },
  { id: 'kec-tawang', parent_id: 'city-tasik-kota', name: 'Tawang', type: 'KECAMATAN', country_code: 'IDN', lat: -7.3280, lng: 108.2280 },
  { id: 'kec-kawalu', parent_id: 'city-tasik-kota', name: 'Kawalu', type: 'KECAMATAN', country_code: 'IDN', lat: -7.3700, lng: 108.2000 },
  { id: 'kec-indihiang', parent_id: 'city-tasik-kota', name: 'Indihiang', type: 'KECAMATAN', country_code: 'IDN', lat: -7.2950, lng: 108.1900 },
];

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    region_id: 'kec-cibeureum',
    name: 'Griya Nugraha',
    developer_name: 'PT Agnia Utama Sejahtera',
    property_type: 'subsidi',
    price: 166000000,
    min_dp: 5000000,
    max_cash_installment_months: 24,
    currency: 'IDR',
    address: 'Jl. K.H. Zabidi, Nagarakasih, Kersanagara, Kec. Cibeureum, Kota Tasikmalaya',
    lat: -7.3460,
    lng: 108.2470,
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80',
    ],
    is_brochure_fallback: true,
    legalities: ['SHM', 'PBG/IMB', 'PBB Pecah'],
    specifications: {
      lb: 36,
      lt: 66,
      kamar_tidur: 2,
      kamar_mandi: 1,
      listrik: '1300W',
      air: 'PDAM / Sumur Bor',
      tahun_dibangun: 2025,
      keamanan: {
        satpam_24jam: true,
        one_gate_system: true,
        cctv_lingkungan: true,
      },
      akses_terdekat: {
        pusat_belanja: ['6 menit ke Plaza Asia Tasikmalaya', '8 menit ke Samudra Supermarket'],
        rumah_sakit: ['7 menit ke RSUD dr. Soekardjo'],
        sekolah: ['4 menit ke SMAN 1 Tasikmalaya'],
        akses_tol: ['15 menit ke Gerbang Tol Getaci'],
      },
    },
    whatsapp_number: '628980578484',
    instagram_url: 'https://instagram.com/griya.nugraha',
  },
  {
    id: 'prop-2',
    region_id: 'kec-cibeureum',
    name: 'Parahyangan Residence (Bumi Parahyangan)',
    developer_name: 'PT Bumi Parahyangan Properti',
    property_type: 'subsidi',
    price: 166000000,
    min_dp: 5000000,
    max_cash_installment_months: 24,
    currency: 'IDR',
    address: 'Kersanagara, Kec. Cibeureum, Kota Tasikmalaya (ID SiKumbang: TSM0610072024T002)',
    lat: -7.3440,
    lng: 108.2430,
    images: [
      '/images/properties/parahyangan-1.jpg',
      '/images/properties/parahyangan-2.jpg',
      '/images/properties/parahyangan-3.jpg',
    ],
    legalities: ['SHM', 'PBG/IMB', 'PBB Pecah'],
    specifications: {
      lb: 36,
      lt: 72,
      kamar_tidur: 2,
      kamar_mandi: 1,
      listrik: '1300W',
      air: 'Artesis / Submersible',
      tahun_dibangun: 2025,
      keamanan: {
        satpam_24jam: true,
        one_gate_system: true,
        cctv_lingkungan: true,
      },
      akses_terdekat: {
        pusat_belanja: ['5 menit ke Plaza Asia Tasikmalaya', '7 menit ke Mayasari Plaza'],
        rumah_sakit: ['6 menit ke RS TMC Tasikmalaya'],
        sekolah: ['3 menit ke SMPN 2 Tasikmalaya'],
        akses_tol: ['12 menit ke Gerbang Tol Getaci'],
      },
    },
    whatsapp_number: '6281234567890',
    instagram_url: 'https://instagram.com/parahyanganresidence',
  },
  {
    id: 'prop-3',
    region_id: 'kec-cibeureum',
    name: 'Pelangi Residence',
    developer_name: 'PT Marhamah Mandiri Jaya (REI)',
    property_type: 'komersil',
    price: 425000000,
    min_dp: 20000000,
    max_cash_installment_months: 18,
    currency: 'IDR',
    address: 'Jl. Letjen Mashudi, Kersanagara, Kec. Cibeureum, Kota Tasikmalaya (ID SiKumbang: TSM0610072020T001)',
    lat: -7.3480,
    lng: 108.2410,
    images: [
      '/images/properties/pelangi-1.jpg',
      '/images/properties/pelangi-2.jpg',
      '/images/properties/pelangi-3.jpg',
    ],
    legalities: ['SHM', 'PBG/IMB', 'PBB Pecah'],
    specifications: {
      lb: 54,
      lt: 90,
      kamar_tidur: 3,
      kamar_mandi: 2,
      listrik: '2200W',
      air: 'PDAM Tirta Sukapura',
      tahun_dibangun: 2025,
      keamanan: {
        satpam_24jam: true,
        one_gate_system: true,
        cctv_lingkungan: true,
      },
      akses_terdekat: {
        pusat_belanja: ['4 menit ke Bandara Wiriadinata', '8 menit ke Plaza Asia Tasikmalaya'],
        rumah_sakit: ['5 menit ke RS Syarif Hidayatullah'],
        sekolah: ['3 menit ke Universitas Siliwangi (UNSIL)'],
        akses_tol: ['10 menit ke Pusat Kota'],
      },
    },
    whatsapp_number: '6281398765432',
    instagram_url: 'https://instagram.com/pelangiresidence.tasik',
  },
  {
    id: 'prop-4',
    region_id: 'kec-indihiang',
    name: 'Grand Metro Indihiang',
    developer_name: 'PT Grand Metro Tasikmalaya',
    property_type: 'komersil',
    price: 550000000,
    min_dp: 25000000,
    max_cash_installment_months: 24,
    currency: 'IDR',
    address: 'Jl. Brigjen Wasita Kusumah, Sukamaju, Kec. Indihiang, Kota Tasikmalaya',
    lat: -7.2960,
    lng: 108.1910,
    images: [
      '/images/properties/grandmetro-1.jpg',
      '/images/properties/grandmetro-2.jpg',
      '/images/properties/grandmetro-3.jpg',
    ],
    legalities: ['SHM', 'PBG/IMB', 'PBB Pecah'],
    specifications: {
      lb: 50,
      lt: 84,
      kamar_tidur: 2,
      kamar_mandi: 1,
      listrik: '1300W',
      air: 'PDAM Tirta Sukapura',
      tahun_dibangun: 2025,
      keamanan: {
        satpam_24jam: true,
        one_gate_system: true,
        cctv_lingkungan: true,
      },
      akses_terdekat: {
        pusat_belanja: ['4 menit ke Terminal Type A Indihiang', '7 menit ke Transmart Tasikmalaya'],
        rumah_sakit: ['6 menit ke RS Islam Tasikmalaya'],
        sekolah: ['3 menit ke SMKN 2 Tasikmalaya'],
        akses_tol: ['5 menit ke Rencana Gerbang Tol Getaci Indihiang'],
      },
    },
    whatsapp_number: '6282112233445',
    instagram_url: 'https://instagram.com/grandmetroindihiang',
  },
  {
    id: 'prop-5',
    region_id: 'kec-kawalu',
    name: 'Istana Kawalu',
    developer_name: 'PT Istana Kawalu Asri',
    property_type: 'subsidi',
    price: 166000000,
    min_dp: 5000000,
    max_cash_installment_months: 12,
    currency: 'IDR',
    address: 'Jl. Raya Kawalu, Karsamenak, Kec. Kawalu, Kota Tasikmalaya',
    lat: -7.3710,
    lng: 108.2010,
    images: [
      '/images/properties/istanakawalu-1.jpg',
      '/images/properties/istanakawalu-2.jpg',
      '/images/properties/istanakawalu-3.jpg',
    ],
    legalities: ['SHM', 'PBG/IMB', 'PBB Pecah'],
    specifications: {
      lb: 36,
      lt: 66,
      kamar_tidur: 2,
      kamar_mandi: 1,
      listrik: '1300W',
      air: 'Sumur Bor Jernih',
      tahun_dibangun: 2025,
      keamanan: {
        satpam_24jam: true,
        one_gate_system: true,
        cctv_lingkungan: true,
      },
      akses_terdekat: {
        pusat_belanja: ['8 menit ke Pasar Kawalu', '12 menit ke Plaza Asia Tasikmalaya'],
        rumah_sakit: ['10 menit ke RSUD dr. Soekardjo'],
        sekolah: ['5 menit ke SMPN 9 Tasikmalaya'],
        akses_tol: ['18 menit ke Jalan Utama'],
      },
    },
    whatsapp_number: '6285711223344',
    instagram_url: 'https://instagram.com/istanakawalu',
  },
];
