'use client';

import React, { createContext, useContext, useState, ReactNode } from 'react';
import { SupportedLanguage } from '@/lib/types';

export interface LanguageOption {
  code: SupportedLanguage;
  label: string;
  flag: string;
  group: 'Global' | 'Daerah Indonesia';
}

export const LANGUAGE_OPTIONS: LanguageOption[] = [
  // Global Languages
  { code: 'id', label: 'Bahasa Indonesia', flag: '🇮🇩', group: 'Global' },
  { code: 'en', label: 'English', flag: '🇺🇸', group: 'Global' },
  { code: 'zh', label: 'Chinese (中文)', flag: '🇨🇳', group: 'Global' },
  { code: 'ms', label: 'Bahasa Melayu', flag: '🇲🇾', group: 'Global' },
  { code: 'fr', label: 'Français', flag: '🇫🇷', group: 'Global' },
  { code: 'th', label: 'Thai (ไทย)', flag: '🇹🇭', group: 'Global' },
  { code: 'ph', label: 'Tagalog (Filipino)', flag: '🇵🇭', group: 'Global' },
  { code: 'ja', label: 'Japanese (日本語)', flag: '🇯🇵', group: 'Global' },
  { code: 'ko', label: 'Korean (한국어)', flag: '🇰🇷', group: 'Global' },
  { code: 'ru', label: 'Russian (Русский)', flag: '🇷🇺', group: 'Global' },

  // Indonesian Regional Languages
  { code: 'su', label: 'Basa Sunda', flag: '🌾', group: 'Daerah Indonesia' },
  { code: 'jv', label: 'Basa Jawa', flag: '🏛️', group: 'Daerah Indonesia' },
  { code: 'min', label: 'Baso Minang', flag: '🏠', group: 'Daerah Indonesia' },
  { code: 'btk', label: 'Hata Batak', flag: '⛰️', group: 'Daerah Indonesia' },
  { code: 'pap', label: 'Bahasa Papua', flag: '🌿', group: 'Daerah Indonesia' },
];

export const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  id: {
    heroTitle: 'Temukan Rumah Impian dengan Legalitas Terjamin',
    heroSubtitlePrefix: 'Cari, bandingkan, dan verifikasi properti di seluruh',
    searchButton: 'Cari Properti',
    country: 'Negara',
    province: 'Provinsi',
    city: 'Kota / Kabupaten',
    district: 'Kecamatan',
    allTypes: 'Semua Tipe',
    subsidi: 'Subsidi',
    komersil: 'Komersil',
    propertyTypeLabel: 'Tipe Properti',
    transparencyLegalities: 'Transparansi Legalitas',
    interactiveMap: 'Peta Interaktif Bumipedia',
    verifiedListings: 'Daftar Properti Terverifikasi',
    bedroomLabel: 'Kamar',
    bathroomLabel: 'Kamar Mandi',
    buildingLabel: 'Bangunan',
    landLabel: 'Tanah',
    noResultsTitle: 'Belum Ada Properti Terdaftar di Wilayah Ini',
    noResultsSubtitle: 'Wilayah ini belum memiliki unit properti terverifikasi dalam database kami.',
    compareButton: 'Bandingkan',
    detailsButton: 'Lihat Detail',
    addComparison: 'Tambah Komparasi',
    comparedBadge: 'Terkomparasi',
    removeComparison: 'Hapus',
    clearAll: 'Hapus Semua',
    calcTitle: 'KPR & Cash Bertahap Simulator',
    finCalcTitle: 'Simulasi Pembiayaan Properti',
    finCalcSubtitle: 'Hitung estimasi angsuran bulanan sesuai skema pembayaran Anda',
    antiTipuBannerTitle: 'Status Legalitas Terjamin ("Anti-Tipu")',
    antiTipuBannerSubtitle: 'Seluruh dokumen hukum untuk unit ini telah diverifikasi keabsahannya:',
    securityAndAccessTitle: 'Fasilitas Keamanan & Akses Terdekat',
    securitySystemTitle: '🛡️ Sistem Keamanan',
    publicAccessTitle: '🚗 Akses Fasilitas Umum',
    developerSocialsTitle: 'Media Sosial Resmi Developer',
    noHiddenFees: '🔒 Tanpa Biaya Tersembunyi • Langsung Terhubung ke Developer Resmi',
    minDpLabel: 'Minimal Uang Muka (DP)',
    kprTab: 'KPR (Bunga Anuitas)',
    cashTab: 'Cash Bertahap (0% Bunga)',
    dpLabel: 'Uang Muka (DP)',
    tenorLabel: 'Jangka Waktu (Tenor)',
    monthlyEstimate: 'Estimasi Angsuran / Bulan',
    antiTipuTitle: 'Legalitas Terjamin',
    scheduleSurvey: 'Jadwalkan Survey Lokasi',
    chatWA: 'Hubungi Marketing via WA',
    favorites: 'Favorit',
    compareMaxWarning: 'Maksimal 3 properti untuk komparasi',
    yes: 'Ya',
    no: 'Tidak',
    securityGuard24h: 'Satpam 24 Jam',
    oneGateSystem: 'One Gate System',
    cctvSurveillance: 'CCTV Lingkungan',
    monthsLabel: 'Bulan',
    monthShort: 'bulan',
    yearsLabel: 'Tahun',
    cashTenorTitle: 'Pilihan Tenor Cash Bertahap',
    cashSchemeNote: 'Skema Cash Bertahap 0% Bunga langsung ke Developer tanpa perantara bank.',
    cashFlatNote: '*Dicicil {count}x flat tanpa bunga tambahan',
    kprInterestFootnote: '*Asumsi Suku Bunga Fixed {rate}% / tahun (Anuitas Bank Syariah / Konvensional)',
    minDpBound: 'Min. DP: {val}',
    maxDpBound: 'Maks. DP (50%): {val}',
    shmName: 'SHM (Sertifikat Hak Milik)',
    shmDesc: 'Legalitas tertinggi & terkuat di Indonesia, hak milik penuh tanpa batas waktu.',
    pbgName: 'PBG / IMB (Izin Bangunan)',
    pbgDesc: 'Izin Resmi Mendirikan Bangunan dari pemerintah daerah setempat.',
    pbbName: 'PBB Pecah Per Kavling',
    pbbDesc: 'Pajak Bumi dan Bangunan sudah terpisah per kavling/unit, siap balik nama.',
    minutesTo: '{min} menit ke {dest}',
  },
  en: {
    heroTitle: 'Find Your Dream Home with Guaranteed Legalities',
    heroSubtitlePrefix: 'Search, compare, and verify properties across',
    searchButton: 'Search Property',
    country: 'Country',
    province: 'Province / State',
    city: 'City / Region',
    district: 'District',
    allTypes: 'All Types',
    subsidi: 'Subsidized',
    komersil: 'Commercial',
    propertyTypeLabel: 'Property Type',
    transparencyLegalities: 'Full Transparency Legalities',
    interactiveMap: 'Bumipedia Interactive Map',
    verifiedListings: 'Verified Property Listings',
    bedroomLabel: 'Bedrooms',
    bathroomLabel: 'Bathrooms',
    buildingLabel: 'Building',
    landLabel: 'Land',
    noResultsTitle: 'No Properties Registered in This Region',
    noResultsSubtitle: 'This region currently has no verified listings in our database.',
    compareButton: 'Compare',
    detailsButton: 'View Details',
    addComparison: 'Add to Compare',
    comparedBadge: 'Compared',
    removeComparison: 'Remove',
    clearAll: 'Clear All',
    calcTitle: 'Mortgage & Installment Simulator',
    finCalcTitle: 'Property Financing Simulator',
    finCalcSubtitle: 'Calculate your estimated monthly installment according to your payment scheme',
    antiTipuBannerTitle: 'Guaranteed Legal Status ("Verified")',
    antiTipuBannerSubtitle: 'All legal documents for this unit have been fully verified:',
    securityAndAccessTitle: 'Security Facilities & Nearby Access',
    securitySystemTitle: '🛡️ Security System',
    publicAccessTitle: '🚗 Public Access',
    developerSocialsTitle: 'Official Developer Social Media',
    noHiddenFees: '🔒 No Hidden Fees • Direct Connection to Official Developer',
    minDpLabel: 'Minimum Down Payment (DP)',
    kprTab: 'Mortgage Loan (KPR)',
    cashTab: 'Cash Installment (0% Interest)',
    dpLabel: 'Down Payment (DP)',
    tenorLabel: 'Loan Tenor',
    monthlyEstimate: 'Est. Monthly Installment',
    antiTipuTitle: 'Verified Legalities',
    scheduleSurvey: 'Schedule Location Survey',
    chatWA: 'Chat Marketing via WA',
    favorites: 'Favorites',
    compareMaxWarning: 'Maximum 3 properties allowed for comparison',
    yes: 'Yes',
    no: 'No',
    securityGuard24h: '24-Hour Security Guard',
    oneGateSystem: 'One Gate System',
    cctvSurveillance: 'Neighborhood CCTV',
    monthsLabel: 'Months',
    monthShort: 'month',
    yearsLabel: 'Years',
    cashTenorTitle: 'Cash Installment Tenor Options',
    cashSchemeNote: 'Direct 0% Interest Cash Installment Scheme directly to Developer without bank intermediary.',
    cashFlatNote: '*Paid in {count}x flat installments without additional interest',
    kprInterestFootnote: '*Assuming Fixed Interest Rate of {rate}% / year (Islamic Annuity / Conventional Bank)',
    minDpBound: 'Min. DP: {val}',
    maxDpBound: 'Max DP (50%): {val}',
    shmName: 'SHM (Freehold Ownership Title)',
    shmDesc: 'Highest & strongest land ownership title in Indonesia with no expiration date.',
    pbgName: 'PBG / IMB (Building Permit)',
    pbgDesc: 'Official Building Approval Certificate issued by local government authorities.',
    pbbName: 'Split Individual PBB Tax',
    pbbDesc: 'Land & Building Tax already separated per individual plot, ready for title transfer.',
    minutesTo: '{min} minutes to {dest}',
  },
  zh: {
    heroTitle: '寻找产权保障的梦想家园',
    heroSubtitlePrefix: '搜索、比较并验证真实房源，遍布',
    searchButton: '搜索房源',
    country: '国家',
    province: '省份',
    city: '城市',
    district: '区域',
    allTypes: '所有类型',
    subsidi: '补贴房',
    komersil: '商业房',
    propertyTypeLabel: '房产类型',
    transparencyLegalities: '全透明产权验证',
    interactiveMap: 'Bumipedia 交互式地图',
    verifiedListings: '已验证房源列表',
    bedroomLabel: '卧室',
    bathroomLabel: '浴室',
    buildingLabel: '建筑面积',
    landLabel: '土地面积',
    noResultsTitle: '该区域暂无房源记录',
    noResultsSubtitle: '该区域目前尚未在我们的数据库中注册验证房源。',
    compareButton: '对比',
    detailsButton: '查看详情',
    addComparison: '加入对比',
    comparedBadge: '已加入对比',
    removeComparison: '删除',
    clearAll: '全部清除',
    calcTitle: '按揭与分期模拟器',
    finCalcTitle: '房产融资模拟器',
    finCalcSubtitle: '根据您的付款方案计算预计月供',
    antiTipuBannerTitle: '产权保障 ("真实认证")',
    antiTipuBannerSubtitle: '该房源的所有法律文件均已通过验证：',
    securityAndAccessTitle: '安保设施与周边交通',
    securitySystemTitle: '🛡️ 安保系统',
    publicAccessTitle: '🚗 周边设施',
    developerSocialsTitle: '开发商官方社交媒体',
    noHiddenFees: '🔒 无隐藏费用 • 直接对接官方开发商',
    minDpLabel: '最低首付 (DP)',
    kprTab: '房贷按揭 (KPR)',
    cashTab: '零息分期 (0% Interest)',
    dpLabel: '首付 (DP)',
    tenorLabel: '分期期限',
    monthlyEstimate: '预估月供',
    antiTipuTitle: '产权保障',
    scheduleSurvey: '预约现场看房',
    chatWA: 'WhatsApp 联系客服',
    favorites: '收藏夹',
    compareMaxWarning: '最多对比 3 套房源',
    yes: '有',
    no: '无',
    securityGuard24h: '24小时保安',
    oneGateSystem: '单出入口系统',
    cctvSurveillance: '社区监控 CCTV',
    monthsLabel: '个月',
    monthShort: '月',
    yearsLabel: '年',
    cashTenorTitle: '零息分期期限选择',
    cashSchemeNote: '零利息分期付款，直接与开发商签约，无需经过银行。',
    cashFlatNote: '*分为 {count} 期固定还款，无额外利息',
    kprInterestFootnote: '*假设固定年利率 {rate}%（伊斯兰/传统银行等额本息）',
    minDpBound: '最低首付: {val}',
    maxDpBound: '最高首付 (50%): {val}',
    shmName: 'SHM (永久所有权证书)',
    shmDesc: '印尼最高级别的永久土地所有权证书，永久有效。',
    pbgName: 'PBG / IMB (施工许可证)',
    pbgDesc: '地方政府颁发的官方合规建筑施工许可证。',
    pbbName: '独立土地房产税 (PBB)',
    pbbDesc: '每套地块的房产税已独立分户，可直接办理过户。',
    minutesTo: '{min} 分钟到达 {dest}',
  },
  ms: {
    heroTitle: 'Cari Rumah Impian dengan Ketulenan Hak Milik',
    heroSubtitlePrefix: 'Cari, bandingkan dan sahkan hartanah sah di seluruh',
    searchButton: 'Cari Hartanah',
    country: 'Negara',
    province: 'Negeri',
    city: 'Bandar',
    district: 'Daerah',
    allTypes: 'Semua Jenis',
    subsidi: 'Subsidi',
    komersil: 'Komersial',
    propertyTypeLabel: 'Jenis Hartanah',
    transparencyLegalities: 'Ketulenan Hak Milik Sah',
    interactiveMap: 'Peta Interaktif Bumipedia',
    verifiedListings: 'Senarai Hartanah Disahkan',
    bedroomLabel: 'Bilik',
    bathroomLabel: 'Bilik Mandi',
    buildingLabel: 'Bangunan',
    landLabel: 'Tanah',
    noResultsTitle: 'Tiada Hartanah Berdaftar di Wilayah Ini',
    noResultsSubtitle: 'Wilayah ini belum mempunyai unit hartanah yang disahkan.',
    compareButton: 'Bandingkan',
    detailsButton: 'Lihat Butiran',
    addComparison: 'Tambah Banding',
    comparedBadge: 'Diberbandingkan',
    removeComparison: 'Padam',
    clearAll: 'Padam Semua',
    calcTitle: 'Simulator Pinjaman & Ansuran',
    finCalcTitle: 'Simulator Pembiayaan Hartanah',
    finCalcSubtitle: 'Kira anggaran ansuran bulanan mengikut skema pembayaran anda',
    antiTipuBannerTitle: 'Status Undang-undang Terjamin',
    antiTipuBannerSubtitle: 'Semua dokumen undang-undang telah disahkan:',
    securityAndAccessTitle: 'Kemudahan Keselamatan & Akses Berdekatan',
    securitySystemTitle: '🛡️ Sistem Keselamatan',
    publicAccessTitle: '🚗 Akses Awam',
    developerSocialsTitle: 'Media Sosial Rasmi Pemaju',
    noHiddenFees: '🔒 Tiada Yuran Tersembunyi • Terus ke Pemaju Rasmi',
    minDpLabel: 'Deposit Minimum (DP)',
    kprTab: 'Pinjaman Perumahan',
    cashTab: 'Ansuran Tunai (0% Faedah)',
    dpLabel: 'Deposit (DP)',
    tenorLabel: 'Tempoh Ansuran',
    monthlyEstimate: 'Anggaran Bulanan',
    antiTipuTitle: 'Ketulenan Hak Milik',
    scheduleSurvey: 'Jadualkan Lawatan',
    chatWA: 'Hubungi WA Marketing',
    favorites: 'Kegemaran',
    compareMaxWarning: 'Maksimum 3 hartanah untuk perbandingan',
    yes: 'Ya',
    no: 'Tidak',
    securityGuard24h: 'Pengawal Keselamatan 24 Jam',
    oneGateSystem: 'Sistem Satu Pintu',
    cctvSurveillance: 'CCTV Kejiranan',
    monthsLabel: 'Bulan',
    monthShort: 'bulan',
    yearsLabel: 'Tahun',
    cashTenorTitle: 'Pilihan Tempoh Ansuran Tunai',
    cashSchemeNote: 'Skim Ansuran Tunai 0% Faedah terus kepada Pemaju tanpa perantara bank.',
    cashFlatNote: '*Bayaran {count}x ansuran tetap tanpa faedah tambahan',
    kprInterestFootnote: '*Andaian Kadar Faedah Tetap {rate}% / tahun (Anuitan Bank Syariah / Konvensional)',
    minDpBound: 'Min. Deposit: {val}',
    maxDpBound: 'Maks. Deposit (50%): {val}',
    shmName: 'SHM (Sijil Hak Milik Kekal)',
    shmDesc: 'Hak milik tanah tertinggi & terkuat di Indonesia tanpa had masa.',
    pbgName: 'PBG / IMB (Kebenaran Bangunan)',
    pbgDesc: 'Kebenaran Resmi Mendirikan Bangunan daripada pihak berkuasa tempatan.',
    pbbName: 'Cukai PBB Berasingan',
    pbbDesc: 'Cukai Tanah & Bangunan telah diasingkan mengikut lot, sedia tukar nama.',
    minutesTo: '{min} minit ke {dest}',
  },
  fr: {
    heroTitle: 'Trouvez votre maison de rêve en toute sécurité',
    heroSubtitlePrefix: 'Recherchez, comparez et vérifiez des propriétés certifiées dans tout',
    searchButton: 'Rechercher',
    country: 'Pays',
    province: 'Région / État',
    city: 'Ville',
    district: 'District',
    allTypes: 'Tous les types',
    subsidi: 'Subventionné',
    komersil: 'Commercial',
    propertyTypeLabel: 'Type de bien',
    transparencyLegalities: 'Transparence Légale',
    interactiveMap: 'Carte Interactive Bumipedia',
    verifiedListings: 'Propriétés Vérifiées',
    bedroomLabel: 'Chambres',
    bathroomLabel: 'Salles de bain',
    buildingLabel: 'Surface',
    landLabel: 'Terrain',
    noResultsTitle: 'Aucune propriété enregistrée dans cette région',
    noResultsSubtitle: 'Cette région ne contient actuellement aucune propriété vérifiée.',
    compareButton: 'Comparer',
    detailsButton: 'Voir détails',
    addComparison: 'Ajouter',
    comparedBadge: 'Comparé',
    removeComparison: 'Supprimer',
    clearAll: 'Tout effacer',
    calcTitle: 'Simulateur d\'Emprunt',
    finCalcTitle: 'Simulateur de Financement Immobilier',
    finCalcSubtitle: 'Calculez vos mensualités estimées selon votre plan',
    antiTipuBannerTitle: 'Statut Légal Garanti',
    antiTipuBannerSubtitle: 'Tous les documents légaux ont été entièrement vérifiés :',
    securityAndAccessTitle: 'Sécurité et Accès Proches',
    securitySystemTitle: '🛡️ Système de Sécurité',
    publicAccessTitle: '🚗 Transports & Commerces',
    developerSocialsTitle: 'Réseaux Sociaux du Promoteur',
    noHiddenFees: '🔒 Sans frais cachés • Directement connecté au promoteur',
    minDpLabel: 'Apport Minimum (DP)',
    kprTab: 'Crédit Immobilier',
    cashTab: 'Paiement Échelonné (0%)',
    dpLabel: 'Apport Personnel',
    tenorLabel: 'Durée',
    monthlyEstimate: 'Mensualité estimée',
    antiTipuTitle: 'Légalités Vérifiées',
    scheduleSurvey: 'Planifier une visite',
    chatWA: 'Contact WA Marketing',
    favorites: 'Favoris',
    compareMaxWarning: 'Maximum 3 propriétés à comparer',
    yes: 'Oui',
    no: 'Non',
    securityGuard24h: 'Garde de sécurité 24h/24',
    oneGateSystem: 'Accès sécurisé unique',
    cctvSurveillance: 'Vidéosurveillance CCTV',
    monthsLabel: 'Mois',
    monthShort: 'mois',
    yearsLabel: 'Ans',
    cashTenorTitle: 'Options de Durée de Paiement',
    cashSchemeNote: 'Plan de paiement échelonné à 0% directement avec le promoteur.',
    cashFlatNote: '*Payable en {count} mensualités fixes sans intérêts',
    kprInterestFootnote: '*Hypothèse de Taux Fixe de {rate}% / an (Banque Islamique / Conventionnelle)',
    minDpBound: 'Apport Min.: {val}',
    maxDpBound: 'Apport Max. (50%): {val}',
    shmName: 'SHM (Titre de Propriété Pleine)',
    shmDesc: 'Le titre de propriété le plus élevé en Indonésie sans limite de durée.',
    pbgName: 'PBG / IMB (Permis de Construire)',
    pbgDesc: 'Autorisation officielle de construction délivrée par le gouvernement local.',
    pbbName: 'Taxe Foncière Individualisée',
    pbbDesc: 'Taxe foncière déjà divisée par lot, prête pour le transfert de propriété.',
    minutesTo: '{min} min. de {dest}',
  },
  th: {
    heroTitle: 'ค้นหาบ้านในฝันพร้อมการรับประกันเอกสารสิทธิ์',
    heroSubtitlePrefix: 'ค้นหา เปรียบเทียบ และตรวจสอบอสังหาริมทรัพย์ที่ถูกต้องทั่ว',
    searchButton: 'ค้นหาอสังหาฯ',
    country: 'ประเทศ',
    province: 'จังหวัด',
    city: 'เมือง',
    district: 'เขต / อำเภอ',
    allTypes: 'ทุกประเภท',
    subsidi: 'บ้านอุดหนุน',
    komersil: 'เชิงพาณิชย์',
    propertyTypeLabel: 'ประเภทอสังหาฯ',
    transparencyLegalities: 'โปร่งใส ตรวจสอบสิทธิ์ได้',
    interactiveMap: 'แผนที่ Bumipedia',
    verifiedListings: 'รายการอสังหาฯ ที่ผ่านการตรวจสอบ',
    bedroomLabel: 'ห้องนอน',
    bathroomLabel: 'ห้องน้ำ',
    buildingLabel: 'พื้นที่ใช้สอย',
    landLabel: 'ขนาดที่ดิน',
    noResultsTitle: 'ยังไม่มีอสังหาริมทรัพย์ที่ลงทะเบียนในพื้นที่นี้',
    noResultsSubtitle: 'พื้นที่นี้ยังไม่มีอสังหาริมทรัพย์ที่ได้รับการตรวจสอบในระบบ',
    compareButton: 'เปรียบเทียบ',
    detailsButton: 'ดูรายละเอียด',
    addComparison: 'เพิ่มการเปรียบเทียบ',
    comparedBadge: 'เปรียบเทียบแล้ว',
    removeComparison: 'ลบ',
    clearAll: 'ลบทั้งหมด',
    calcTitle: 'เครื่องมือคำนวณสินเชื่อ',
    finCalcTitle: 'เครื่องมือคำนวณการผ่อนชำระ',
    finCalcSubtitle: 'คำนวณค่างวดผ่อนชำระต่อเดือนตามแผนของคุณ',
    antiTipuBannerTitle: 'รับประกันความถูกต้องของเอกสาร',
    antiTipuBannerSubtitle: 'เอกสารสิทธิ์ทั้งหมดได้รับการตรวจสอบแล้ว:',
    securityAndAccessTitle: 'ระบบรักษาความปลอดภัยและการเดินทาง',
    securitySystemTitle: '🛡️ ระบบรักษาความปลอดภัย',
    publicAccessTitle: '🚗 สถานที่ใกล้เคียง',
    developerSocialsTitle: 'โซเชียลมีเดียอย่างเป็นทางการของผู้พัฒนา',
    noHiddenFees: '🔒 ไม่มีค่าธรรมเนียมแอบแฝง • ติดต่อโครงการโดยตรง',
    minDpLabel: 'เงินดาวน์ขั้นต่ำ',
    kprTab: 'สินเชื่อบ้าน (KPR)',
    cashTab: 'ผ่อนชำระสด (ดอกเบี้ย 0%)',
    dpLabel: 'เงินดาวน์ (DP)',
    tenorLabel: 'ระยะเวลาผ่อน',
    monthlyEstimate: 'ประมาณการผ่อนต่อเดือน',
    antiTipuTitle: 'เอกสารสิทธิ์ถูกต้อง',
    scheduleSurvey: 'นัดหมายเข้าชม',
    chatWA: 'ติดต่อการตลาด via WA',
    favorites: 'รายการโปรด',
    compareMaxWarning: 'เปรียบเทียบได้สูงสุด 3 รายการ',
    yes: 'มี',
    no: 'ไม่มี',
    securityGuard24h: 'รปภ. 24 ชั่วโมง',
    oneGateSystem: 'ระบบเข้า-ออกทางเดียว',
    cctvSurveillance: 'กล้องวงจรปิดรอบโครงการ',
    monthsLabel: 'เดือน',
    monthShort: 'เดือน',
    yearsLabel: 'ปี',
    cashTenorTitle: 'ตัวเลือกระยะเวลาผ่อนสด',
    cashSchemeNote: 'ผ่อนชำระตรงกับโครงการ ดอกเบี้ย 0% ไม่ผ่านธนาคาร',
    cashFlatNote: '*ผ่อนชำระ {count} งวดเท่ากัน ไม่มีดอกเบี้ยเพิ่ม',
    kprInterestFootnote: '*สมมติอัตราดอกเบี้ยคงที่ {rate}% / ปี (อนูอิตีธนาคารอิสลาม / พาณิชย์)',
    minDpBound: 'เงินดาวน์ขั้นต่ำ: {val}',
    maxDpBound: 'เงินดาวน์สูงสุด (50%): {val}',
    shmName: 'SHM (โฉนดที่ดินกรรมสิทธิ์สมบูรณ์)',
    shmDesc: 'เอกสารสิทธิ์สูงสุดในอินโดนีเซีย ถือครองได้ตลอดชีพ',
    pbgName: 'PBG / IMB (ใบอนุญาตก่อสร้าง)',
    pbgDesc: 'ใบอนุญาตก่อสร้างอย่างเป็นทางการจากหน่วยงานท้องถิ่น',
    pbbName: 'ภาษีที่ดินแยกแปลง (PBB)',
    pbbDesc: 'ภาษีที่ดินและสิ่งปลูกสร้างโอนแยกแปลงแล้ว พร้อมโอนสิทธิ์',
    minutesTo: '{min} นาทีถึง {dest}',
  },
  ph: {
    heroTitle: 'Hanapin ang Bahay ng Pangarap mo nang may Garantisadong Legalidad',
    heroSubtitlePrefix: 'Maghanap, maghambing, at mag-verify ng ari-arian sa buong',
    searchButton: 'Maghanap',
    country: 'Bansa',
    province: 'Lalawigan',
    city: 'Lungsod',
    district: 'Distrito',
    allTypes: 'Lahat ng Uri',
    subsidi: 'Subsidized',
    komersil: 'Komersyal',
    propertyTypeLabel: 'Uri ng Ari-arian',
    transparencyLegalities: 'Garantisadong Legalidad',
    interactiveMap: 'Bumipedia Interactive Map',
    verifiedListings: 'Mga Ari-ariang Veripikado',
    bedroomLabel: 'Silid-tulugan',
    bathroomLabel: 'Banyo',
    buildingLabel: 'Laki ng Bahay',
    landLabel: 'Laki ng Lupa',
    noResultsTitle: 'Walang Nakarehistrong Ari-arian sa Rehiyong Ito',
    noResultsSubtitle: 'Ang rehiyong ito ay wala pang nakarehistrong unit sa aming database.',
    compareButton: 'Ipaghambing',
    detailsButton: 'Tingnan ang Detalye',
    addComparison: 'Idagdag',
    comparedBadge: 'Naipaghambing Na',
    removeComparison: 'Alisin',
    clearAll: 'Alisin Lahat',
    calcTitle: 'KPR at Installment Simulator',
    finCalcTitle: 'Financing Simulator',
    finCalcSubtitle: 'Kalkulahin ang tantyang buwanang hulog',
    antiTipuBannerTitle: 'Garantisadong Legalidad',
    antiTipuBannerSubtitle: 'Ang lahat ng legal na dokumento ay nakumpleto na:',
    securityAndAccessTitle: 'Pasilidad ng Seguridad at Malapit na Akses',
    securitySystemTitle: '🛡️ Sistema ng Seguridad',
    publicAccessTitle: '🚗 Akses sa Pampublikong Pasilidad',
    developerSocialsTitle: 'Opisyal na Social Media ng Developer',
    noHiddenFees: '🔒 Walang Nakatagong Bayad • Direktang Konektado sa Developer',
    minDpLabel: 'Minimum na Down Payment (DP)',
    kprTab: 'Housing Loan',
    cashTab: 'Hulugan (0% Interes)',
    dpLabel: 'Down Payment (DP)',
    tenorLabel: 'Tagal ng Hulog',
    monthlyEstimate: 'Tantyang Hulog Buwan-buwan',
    antiTipuTitle: 'Legalidad Garantisado',
    scheduleSurvey: 'Mag-iskedyul ng Bisita',
    chatWA: 'Kausapin ang Marketing sa WA',
    favorites: 'Paborito',
    compareMaxWarning: 'Hanggang 3 ari-arian lamang ang pwedeng paghambingin',
    yes: 'Mayroon',
    no: 'Wala',
    securityGuard24h: '24-Oras na Gwardya',
    oneGateSystem: 'One Gate System',
    cctvSurveillance: 'CCTV sa Paligid',
    monthsLabel: 'Buwan',
    monthShort: 'buwan',
    yearsLabel: 'Taon',
    cashTenorTitle: 'Pagpipilian sa Tagal ng Hulugan',
    cashSchemeNote: 'Direktang hulugan na 0% interes sa Developer nang walang bangko.',
    cashFlatNote: '*Hulugan sa loob ng {count} buwan nang walang dagdag interes',
    kprInterestFootnote: '*Inaasahang Fixed Interest Rate na {rate}% / taon (Islamic / Conventional Bank)',
    minDpBound: 'Min. DP: {val}',
    maxDpBound: 'Max DP (50%): {val}',
    shmName: 'SHM (Ganap na Titulo ng Lupa)',
    shmDesc: 'Pinakamataas at pinakamalakas na titulo ng lupa sa Indonesia.',
    pbgName: 'PBG / IMB (Permiso sa Pagtatayo)',
    pbgDesc: 'Opisyal na permiso sa pagtatayo mula sa lokal na pamahalaan.',
    pbbName: 'Hiwalay na Buwis sa Lupa (PBB)',
    pbbDesc: 'Nakahiwalay na ang buwis bawat lote, handa na sa paglipat ng titulo.',
    minutesTo: '{min} minuto papuntang {dest}',
  },
  ja: {
    heroTitle: '権利関係検証済みの理想の住まいを見つけよう',
    heroSubtitlePrefix: 'エリア全域の公式検証済み物件を検索・比較・確認',
    searchButton: '物件を検索',
    country: '国',
    province: '都道府県 / 州',
    city: '市区町村',
    district: '地区',
    allTypes: 'すべてのタイプ',
    subsidi: '補助金対象住宅',
    komersil: '一般分譲住宅',
    propertyTypeLabel: '物件タイプ',
    transparencyLegalities: '権利関係完全透明',
    interactiveMap: 'Bumipedia インタラクティブマップ',
    verifiedListings: '検証済み物件一覧',
    bedroomLabel: '寝室',
    bathroomLabel: '浴室・トイレ',
    buildingLabel: '建物面積',
    landLabel: '土地面積',
    noResultsTitle: 'この地域には登録物件がありません',
    noResultsSubtitle: 'この地域には現在データベースに登録された検証済み物件がありません。',
    compareButton: '物件比較',
    detailsButton: '詳細を見る',
    addComparison: '比較に追加',
    comparedBadge: '比較済み',
    removeComparison: '削除',
    clearAll: 'すべてクリア',
    calcTitle: '住宅ローン＆分割シミュレーター',
    finCalcTitle: '資金計画シミュレーター',
    finCalcSubtitle: '支払いプランに応じた月々の返済概算を試算します',
    antiTipuBannerTitle: '権利関係完全保証',
    antiTipuBannerSubtitle: 'すべての法的権利書類は検証済みです：',
    securityAndAccessTitle: 'セキュリティ施設と周辺アクセス',
    securitySystemTitle: '🛡️ セキュリティ体制',
    publicAccessTitle: '🚗 周辺アクセス',
    developerSocialsTitle: 'デベロッパー公式SNS',
    noHiddenFees: '🔒 隠れ費用なし • デベロッパー公式直結',
    minDpLabel: '最低頭金 (DP)',
    kprTab: '住宅ローン (KPR)',
    cashTab: '金利0%分割払い',
    dpLabel: '頭金 (DP)',
    tenorLabel: '返済期間',
    monthlyEstimate: '月々の支払概算',
    antiTipuTitle: '権利書・権利関係検証済み',
    scheduleSurvey: '見学を予約',
    chatWA: 'WhatsAppで問い合わせ',
    favorites: 'お気に入り',
    compareMaxWarning: '最大3件まで比較できます',
    yes: 'あり',
    no: 'なし',
    securityGuard24h: '24時間警備員配置',
    oneGateSystem: 'ワンゲートセキュリティ',
    cctvSurveillance: '防犯CCTVカメラ完備',
    monthsLabel: 'ヶ月',
    monthShort: 'ヶ月',
    yearsLabel: '年',
    cashTenorTitle: '分割払い期間の選択',
    cashSchemeNote: '銀行を通さずデベロッパー直接契約の金利0%分割払いプラン。',
    cashFlatNote: '*追加金利なしの {count} 回固定分割払い',
    kprInterestFootnote: '*固定金利年{rate}%（イスラム/従来型銀行等額返済）を想定',
    minDpBound: '最低頭金: {val}',
    maxDpBound: '上限頭金 (50%): {val}',
    shmName: 'SHM (永久所有権証明書)',
    shmDesc: 'インドネシアにおける最高位の完全土地所有権証明書（無期限）。',
    pbgName: 'PBG / IMB (建築許可証)',
    pbgDesc: '地方自治体発行の公式な建築許可証明書。',
    pbbName: '個別土地建物件税 (PBB)',
    pbbDesc: '各区画ごとに固定資産税が分割済み、名義変更可能。',
    minutesTo: '{dest}まで{min}分',
  },
  ko: {
    heroTitle: '권리관계가 검증된 꿈의 집을 찾아보세요',
    heroSubtitlePrefix: '검증된 검증 매물을 검색, 비교 및 확인하세요:',
    searchButton: '매물 검색',
    country: '국가',
    province: '도 / 주',
    city: '시 / 군',
    district: '구 / 읍',
    allTypes: '모든 유형',
    subsidi: '정부 보조 주택',
    komersil: '일반 분양',
    propertyTypeLabel: '매물 유형',
    transparencyLegalities: '권리관계 100% 투명 검증',
    interactiveMap: 'Bumipedia 대화형 지점 지도',
    verifiedListings: '검증 완료 매물 목록',
    bedroomLabel: '방',
    bathroomLabel: '욕실',
    buildingLabel: '건물 면적',
    landLabel: '대지 면적',
    noResultsTitle: '이 지역에 등록된 매물이 없습니다',
    noResultsSubtitle: '현재 이 지역에는 등록된 매물이 없습니다.',
    compareButton: '매물 비교',
    detailsButton: '상세보기',
    addComparison: '비교함 담기',
    comparedBadge: '비교함 추가됨',
    removeComparison: '삭제',
    clearAll: '전체 삭제',
    calcTitle: '대출 & 분할납부 시뮬레이터',
    finCalcTitle: '자금 조달 시뮬레이터',
    finCalcSubtitle: '납입 플랜에 따른 월 납입금을 계산해보세요',
    antiTipuBannerTitle: '권리관계 보증',
    antiTipuBannerSubtitle: '모든 법적 서류가 검증되었습니다:',
    securityAndAccessTitle: '보안 시설 및 주변 접근성',
    securitySystemTitle: '🛡️ 보안 시스템',
    publicAccessTitle: '🚗 주변 주요 시설',
    developerSocialsTitle: '시행사 공식 소셜 미디어',
    noHiddenFees: '🔒 수수료 없음 • 시행사 직접 연결',
    minDpLabel: '최저 선납금 (DP)',
    kprTab: '주택담보대출 (KPR)',
    cashTab: '무이자 분할납부 (0%)',
    dpLabel: '계약금 / 선납금',
    tenorLabel: '대출 기간',
    monthlyEstimate: '예상 월 납입금',
    antiTipuTitle: '권리관계 검증 완료',
    scheduleSurvey: '방문 일정 예약',
    chatWA: 'WhatsApp 상담하기',
    favorites: '보관함',
    compareMaxWarning: '최대 3개 매물까지 비교 가능합니다',
    yes: '있음',
    no: '없음',
    securityGuard24h: '24시간 경비원 배치',
    oneGateSystem: '원 게이트 보안 시스템',
    cctvSurveillance: '단지 내 CCTV',
    monthsLabel: '개월',
    monthShort: '개월',
    yearsLabel: '년',
    cashTenorTitle: '분할납부 기간 선택',
    cashSchemeNote: '은행 대출 없이 시행사 직접 계약 무이자 (0%) 분할납부.',
    cashFlatNote: '*추가 이자 없이 {count}회 균등 분할 납부',
    kprInterestFootnote: '*고정 금리 연 {rate}% 가정 (이스람/시중은행 원리금균등상환)',
    minDpBound: '최소 선납금: {val}',
    maxDpBound: '최대 선납금 (50%): {val}',
    shmName: 'SHM (영구 소유권 증서)',
    shmDesc: '인도네시아 최고 등급의 기한 없는 영구 토지 소유권 증서.',
    pbgName: 'PBG / IMB (건축 허가서)',
    pbgDesc: '지방 정부 발급 정식 건축 허가 증명서.',
    pbbName: '필지별 분할 재산세 (PBB)',
    pbbDesc: '필지별 재산세 분할 완료, 즉시 명의 이전 가능.',
    minutesTo: '{dest}까지 {min}분',
  },
  ru: {
    heroTitle: 'Найдите дом своей мечты с гарантированными юридическими документами',
    heroSubtitlePrefix: 'Поиск, сравнение и проверка проверенных объектов недвижимости по всему',
    searchButton: 'Искать недвижимость',
    country: 'Страна',
    province: 'Область / Штат',
    city: 'Город',
    district: 'Район',
    allTypes: 'Все типы',
    subsidi: 'Субсидированное',
    komersil: 'Коммерческое',
    propertyTypeLabel: 'Тип недвижимости',
    transparencyLegalities: 'Проверенная юридическая чистота',
    interactiveMap: 'Интерактивная карта Bumipedia',
    verifiedListings: 'Проверенная недвижимость',
    bedroomLabel: 'Спальни',
    bathroomLabel: 'Ванные',
    buildingLabel: 'Площадь дома',
    landLabel: 'Площадь участка',
    noResultsTitle: 'В этом регионе нет зарегистрированных объектов',
    noResultsSubtitle: 'В этом регионе пока нет проверенных объектов в нашей базе данных.',
    compareButton: 'Сравнить',
    detailsButton: 'Подробнее',
    addComparison: 'Добавить в сравнение',
    comparedBadge: 'В сравнении',
    removeComparison: 'Удалить',
    clearAll: 'Очистить все',
    calcTitle: 'Калькулятор ипотеки и рассрочки',
    finCalcTitle: 'Калькулятор финансирования',
    finCalcSubtitle: 'Рассчитайте примерный ежемесячный платеж',
    antiTipuBannerTitle: 'Гарантированная юридическая чистота',
    antiTipuBannerSubtitle: 'Все юридические документы были полностью проверены:',
    securityAndAccessTitle: 'Безопасность и Инфраструктура',
    securitySystemTitle: '🛡️ Система безопасности',
    publicAccessTitle: '🚗 Транспорт и инфраструктура',
    developerSocialsTitle: 'Официальные соцсети застройщика',
    noHiddenFees: '🔒 Без скрытых комиссий • Прямая связь с застройщиком',
    minDpLabel: 'Минимальный взнос (DP)',
    kprTab: 'Ипотека (KPR)',
    cashTab: 'Беспроцентная рассрочка (0%)',
    dpLabel: 'Первоначальный взнос',
    tenorLabel: 'Срок рассрочки',
    monthlyEstimate: 'Расчетный ежемесячный платеж',
    antiTipuTitle: 'Проверенные документы',
    scheduleSurvey: 'Записаться на просмотр',
    chatWA: 'Связаться через WhatsApp',
    favorites: 'Избранное',
    compareMaxWarning: 'Максимум 3 объекта для сравнения',
    yes: 'Да',
    no: 'Нет',
    securityGuard24h: 'Круглосуточная охрана',
    oneGateSystem: 'Охраняемый въезд (One Gate)',
    cctvSurveillance: 'Видеонаблюдение CCTV',
    monthsLabel: 'Месяцев',
    monthShort: 'мес.',
    yearsLabel: 'Лет',
    cashTenorTitle: 'Варианты рассрочки',
    cashSchemeNote: 'Рассрочка под 0% напрямую от застройщика без участия банка.',
    cashFlatNote: '*Рассрочка равными долями на {count} мес. без переплат',
    kprInterestFootnote: '*Предполагаемая фиксированная ставка {rate}% / год (Исламский / Обычный банк)',
    minDpBound: 'Мин. взнос: {val}',
    maxDpBound: 'Макс. взнос (50%): {val}',
    shmName: 'SHM (Право собственности)',
    shmDesc: 'Высшая категория права собственности на землю в Индонезии (бессрочно).',
    pbgName: 'PBG / IMB (Разрешение на строительство)',
    pbgDesc: 'Официальное разрешение на строительство от местных властей.',
    pbbName: 'Разделенный налог на имущество (PBB)',
    pbbDesc: 'Налог на землю и здание уже разделен по участкам, готов к переоформлению.',
    minutesTo: '{min} мин. до {dest}',
  },

  // Regional Indonesian Languages
  su: {
    heroTitle: 'Panggihan Imah Impian Kalawan Surat-Surat Terjamin',
    heroSubtitlePrefix: 'Pariksa, bandingkeun, tur verifikasi boga imah halal di sadaya',
    searchButton: 'Cari Imah',
    country: 'Nagara',
    province: 'Provinsi',
    city: 'Kota / Kabupaten',
    district: 'Kecamatan',
    allTypes: 'Sadaya Tipe',
    subsidi: 'Subsidi',
    komersil: 'Komersil',
    propertyTypeLabel: 'Tipe Imah',
    transparencyLegalities: 'Legalitas Terjamin Pasih',
    interactiveMap: 'Peta Pilihan Bumipedia',
    verifiedListings: 'Daptar Imah Terverifikasi',
    bedroomLabel: 'Kamar',
    bathroomLabel: 'Kamar Mandi',
    buildingLabel: 'Wangunan',
    landLabel: 'Taneuh',
    noResultsTitle: 'Acan Aya Imah Kadaptar di Wilayah Ieu',
    noResultsSubtitle: 'Wilayah ieu acan ngagaduhan unit perumahan anu terdaftar dina database.',
    compareButton: 'Bandingkeun',
    detailsButton: 'Tingali Detail',
    addComparison: 'Tambah Banding',
    comparedBadge: 'Geus Dibandingkeun',
    removeComparison: 'Hapus',
    clearAll: 'Hapus Sadaya',
    calcTitle: 'Simulasi KPR & Cicilan',
    finCalcTitle: 'Simulasi Pembiayaan Imah',
    finCalcSubtitle: 'Ngitung prakiraan cicilan sasih nurutkeun skema anjeun',
    antiTipuBannerTitle: 'Status Legalitas Terjamin Pasih',
    antiTipuBannerSubtitle: 'Sadaya dokumen hukum pikeun unit ieu tos di-verifikasi:',
    securityAndAccessTitle: 'Fasilitas Kaamanan & Akses Pangcaketna',
    securitySystemTitle: '🛡️ Sistem Kaamanan',
    publicAccessTitle: '🚗 Akses Fasilitas Umum',
    developerSocialsTitle: 'Média Sosial Resmi Pangembang',
    noHiddenFees: '🔒 Teu Aya Biaya Sumput • Langsung ka Pangembang Resmi',
    minDpLabel: 'Uang Muka Minimal (DP)',
    kprTab: 'KPR (Bunga Anuitas)',
    cashTab: 'Cicilan Bertahap (Bunga 0%)',
    dpLabel: 'Uang Muka (DP)',
    tenorLabel: 'Jangka Waktu (Tenor)',
    monthlyEstimate: 'Prakiraan Angsuran / Sasih',
    antiTipuTitle: 'Legalitas Terjamin',
    scheduleSurvey: 'Jadwal ku Survey',
    chatWA: 'Chat Marketing via WA',
    favorites: 'Pilihan Resep',
    compareMaxWarning: 'Maksimal 3 imah pikeun dibandingkeun',
    yes: 'Enya',
    no: 'Henteu',
    securityGuard24h: 'Satpam 24 Jam',
    oneGateSystem: 'One Gate System',
    cctvSurveillance: 'CCTV Lingkungan',
    monthsLabel: 'Sasih',
    monthShort: 'sasih',
    yearsLabel: 'Taun',
    cashTenorTitle: 'Pilihan Tenor Cash Bertahap',
    cashSchemeNote: 'Cicilan Cash Bertahap Bunga 0% langsung ka Pangembang tanpa perantara bank.',
    cashFlatNote: '*Dicicil {count}x flat teu aya bunga tambahan',
    kprInterestFootnote: '*Prakiraan Bunga Adep {rate}% / taun (Anuitas Bank Syariah / Konvensional)',
    minDpBound: 'Min. DP: {val}',
    maxDpBound: 'Maks. DP (50%): {val}',
    shmName: 'SHM (Sertifikat Hak Milik)',
    shmDesc: 'Legalitas pangluhurna di Indonesia, hak milik pinuh tanpa wates.',
    pbgName: 'PBG / IMB (Izin Bangunan)',
    pbgDesc: 'Izin Resmi Ngadegkeun Bangunan ti pamarentah daerah.',
    pbbName: 'PBB Pecah Per Kavling',
    pbbDesc: 'Pajeg Bumi jeung Bangunan tos terpisah per kavling, siap balik nama.',
    minutesTo: '{min} menit ka {dest}',
  },
  jv: {
    heroTitle: 'Goleki Omah Impian Kanthi Surat-Surat Aman',
    heroSubtitlePrefix: 'Golek, bandingake, lan verifikasi omah legal ing saindhenging',
    searchButton: 'Golek Omah',
    country: 'Negara',
    province: 'Provinsi',
    city: 'Kota / Kabupaten',
    district: 'Kecamatan',
    allTypes: 'Kabeh Tipe',
    subsidi: 'Subsidi',
    komersil: 'Komersil',
    propertyTypeLabel: 'Tipe Omah',
    transparencyLegalities: 'Legalitas Terjamin Safe',
    interactiveMap: 'Peta Interaktif Bumipedia',
    verifiedListings: 'Daftar Omah Terverifikasi',
    bedroomLabel: 'Kamar',
    bathroomLabel: 'Kamar Mandi',
    buildingLabel: 'Bangunan',
    landLabel: 'Lahan',
    noResultsTitle: 'Durung Ana Omah Terdaftar ing Wilayah Iki',
    noResultsSubtitle: 'Wilayah iki durung duwe unit omah terdaftar ing database kita.',
    compareButton: 'Bandingke',
    detailsButton: 'Deleng Detail',
    addComparison: 'Tambah Banding',
    comparedBadge: 'Wis Dibandingke',
    removeComparison: 'Busal',
    clearAll: 'Busal Kabeh',
    calcTitle: 'Simulasi KPR & Angsuran',
    finCalcTitle: 'Simulasi Pembiayaan Omah',
    finCalcSubtitle: 'Hitung prakiraan angsuran saben sasi',
    antiTipuBannerTitle: 'Status Legalitas Terjamin Aman',
    antiTipuBannerSubtitle: 'Kabeh dokumen hukum unit iki wis terverifikasi:',
    securityAndAccessTitle: 'Fasilitas Keamanan & Akses Paling Cedhak',
    securitySystemTitle: '🛡️ Sistem Keamanan',
    publicAccessTitle: '🚗 Akses Fasilitas Umum',
    developerSocialsTitle: 'Media Sosial Resmi Pengembang',
    noHiddenFees: '🔒 Tanpa Biaya Singotan • Langsung menyang Pengembang Resmi',
    minDpLabel: 'Uang Muka Minimal (DP)',
    kprTab: 'KPR (Bunga Anuitas)',
    cashTab: 'Angsuran Bertahap (0% Bunga)',
    dpLabel: 'Uang Muka (DP)',
    tenorLabel: 'Jangka Wektu',
    monthlyEstimate: 'Perkiraan Angsuran / Sasi',
    antiTipuTitle: 'Legalitas Aman',
    scheduleSurvey: 'Jadwalake Survey',
    chatWA: 'Hubungi WA Marketing',
    favorites: 'Kesenengan',
    compareMaxWarning: 'Maksimal 3 omah kanggo dibandhingake',
    yes: 'Iyo',
    no: 'Ora',
    securityGuard24h: 'Satpam 24 Jam',
    oneGateSystem: 'One Gate System',
    cctvSurveillance: 'CCTV Lingkungan',
    monthsLabel: 'Sasi',
    monthShort: 'sasi',
    yearsLabel: 'Tahun',
    cashTenorTitle: 'Pilihan Tenor Cash Bertahap',
    cashSchemeNote: 'Skema Angsuran Cash 0% Bunga langsung menyang Pengembang tanpa bank.',
    cashFlatNote: '*Dicicil {count}x flat tanpa bunga tambahan',
    kprInterestFootnote: '*Asumsi Bunga Tetep {rate}% / tahun (Anuitas Bank Syariah / Konvensional)',
    minDpBound: 'Min. DP: {val}',
    maxDpBound: 'Maks. DP (50%): {val}',
    shmName: 'SHM (Sertifikat Hak Milik)',
    shmDesc: 'Legalitas paling dhuwur ing Indonesia, hak milik penuh tanpa wates.',
    pbgName: 'PBG / IMB (Ijin Bangunan)',
    pbgDesc: 'Ijin Resmi Ngedirake Bangunan saka pemerintah daerah.',
    pbbName: 'PBB Pecah Per Kavling',
    pbbDesc: 'Pajek Bumi lan Bangunan wis terpisah per kavling, siap balik nama.',
    minutesTo: '{min} menit menyang {dest}',
  },
  min: {
    heroTitle: 'Cari Rumah Impian jo Surat-Surat Aman',
    heroSubtitlePrefix: 'Cari, bandingkan, jo verifikasi properti aman di sadolah',
    searchButton: 'Cari Rumah',
    country: 'Nagari',
    province: 'Provinsi',
    city: 'Kota / Kabupaten',
    district: 'Kecamatan',
    allTypes: 'Sado Tipe',
    subsidi: 'Subsidi',
    komersil: 'Komersil',
    propertyTypeLabel: 'Tipe Rumah',
    transparencyLegalities: 'Surat-Surat Aman Resmi',
    interactiveMap: 'Peta Interaktif Bumipedia',
    verifiedListings: 'Daftar Rumah Terverifikasi',
    bedroomLabel: 'Bilik',
    bathroomLabel: 'Kamar Mandi',
    buildingLabel: 'Bangunan',
    landLabel: 'Tanah',
    noResultsTitle: 'Batuang Ado Rumah Terdaftar di Wilayah Ko',
    noResultsSubtitle: 'Wilayah ko durung ado unit terdaftar di database kami.',
    compareButton: 'Bandingkan',
    detailsButton: 'Tingok Detail',
    addComparison: 'Tambah Banding',
    comparedBadge: 'Lah Dibandingkan',
    removeComparison: 'Hapus',
    clearAll: 'Hapus Sadonyo',
    calcTitle: 'Simulasi KPR & Cicilan',
    finCalcTitle: 'Simulasi Pembiayaan Rumah',
    finCalcSubtitle: 'Hitung estimasi cicilan per bulan',
    antiTipuBannerTitle: 'Status Legalitas Terjamin Aman',
    antiTipuBannerSubtitle: 'Sadolah dokumen hukum untuak unit ko lah di-verifikasi:',
    securityAndAccessTitle: 'Fasilitas Keamanan & Akses Paliang Dakek',
    securitySystemTitle: '🛡️ Sistem Keamanan',
    publicAccessTitle: '🚗 Akses Fasilitas Umum',
    developerSocialsTitle: 'Media Sosial Resmi Developer',
    noHiddenFees: '🔒 Ndak Ado Biaya Tapasok • Langsung ka Developer Resmi',
    minDpLabel: 'Uang Muka Minimal (DP)',
    kprTab: 'KPR (Bunga Anuitas)',
    cashTab: 'Cicilan Bertahap (0% Bunga)',
    dpLabel: 'Uang Muka (DP)',
    tenorLabel: 'Jangka Waktu',
    monthlyEstimate: 'Estimasi Cicilan / Bulan',
    antiTipuTitle: 'Surat-Surat Aman',
    scheduleSurvey: 'Jadwalkan Survey',
    chatWA: 'Kirim Pesan WA',
    favorites: 'Rumah Rancak',
    compareMaxWarning: 'Paling banyak 3 rumah untuak dibandingkan',
    yes: 'Iyo',
    no: 'Indak',
    securityGuard24h: 'Satpam 24 Jam',
    oneGateSystem: 'One Gate System',
    cctvSurveillance: 'CCTV Lingkungan',
    monthsLabel: 'Bulan',
    monthShort: 'bulan',
    yearsLabel: 'Tahun',
    cashTenorTitle: 'Pilihan Tenor Cash Bertahap',
    cashSchemeNote: 'Skema Cash Bertahap 0% Bunga langsung ka Developer tanpa perantara bank.',
    cashFlatNote: '*Dicicil {count}x flat tanpa bunga tambahan',
    kprInterestFootnote: '*Estimasi Bunga Tetap {rate}% / tahun (Anuitas Bank Syariah / Konvensional)',
    minDpBound: 'Min. DP: {val}',
    maxDpBound: 'Maks. DP (50%): {val}',
    shmName: 'SHM (Sertifikat Hak Milik)',
    shmDesc: 'Legalitas tertinggi di Indonesia, hak milik penuh tanpa batas.',
    pbgName: 'PBG / IMB (Izin Bangunan)',
    pbgDesc: 'Izin Resmi Mendirikan Bangunan dari pemerintah daerah.',
    pbbName: 'PBB Pecah Per Kavling',
    pbbDesc: 'Pajak Bumi dan Bangunan lah terpisah per kavling, siap balik nama.',
    minutesTo: '{min} menit ka {dest}',
  },
  btk: {
    heroTitle: 'Luluan Bagas Ngarim Dohot Surat Sah',
    heroSubtitlePrefix: 'Luluan, patudoshon, jala verifikasi jabu sah di sude',
    searchButton: 'Luluan Jabu',
    country: 'Negara',
    province: 'Provinsi',
    city: 'Kota / Kabupaten',
    district: 'Kecamatan',
    allTypes: 'Sude Tipe',
    subsidi: 'Subsidi',
    komersil: 'Komersil',
    propertyTypeLabel: 'Tipe Jabu',
    transparencyLegalities: 'Surat-Surat Sah Lengkap',
    interactiveMap: 'Peta Interaktif Bumipedia',
    verifiedListings: 'Daftar Jabu Terverifikasi',
    bedroomLabel: 'Kamar',
    bathroomLabel: 'Kamar Mandi',
    buildingLabel: 'Bagas',
    landLabel: 'Tano',
    noResultsTitle: 'Dung Adong Jabu Terdaftar di Wilayah On',
    noResultsSubtitle: 'Wilayah on dang adong dope jabu terdaftar di database nami.',
    compareButton: 'Patudoshon',
    detailsButton: 'Bereng Detail',
    addComparison: 'Tambai Patudos',
    comparedBadge: 'Nunga Dipatudos',
    removeComparison: 'Sosa',
    clearAll: 'Sosa Sude',
    calcTitle: 'Simulasi KPR & Cicilan',
    finCalcTitle: 'Simulasi Pembiayaan Jabu',
    finCalcSubtitle: 'Etek estimasi gararan ganup bulan',
    antiTipuBannerTitle: 'Status Legalitas Sah Terjamin',
    antiTipuBannerSubtitle: 'Sude dokumen hukum unit on nunga terverifikasi:',
    securityAndAccessTitle: 'Fasilitas Keamanan & Akses Na Jonok',
    securitySystemTitle: '🛡️ Sistem Keamanan',
    publicAccessTitle: '🚗 Akses Fasilitas Umum',
    developerSocialsTitle: 'Media Sosial Resmi Developer',
    noHiddenFees: '🔒 Dang Adong Biaya Na Buni • Langsung tu Developer Resmi',
    minDpLabel: 'Uang Muka Minimal (DP)',
    kprTab: 'KPR (Bunga Anuitas)',
    cashTab: 'Cicilan Bertahap (0% Bunga)',
    dpLabel: 'Uang Muka (DP)',
    tenorLabel: 'Jangka Waktu',
    monthlyEstimate: 'Estimasi Garar / Bulan',
    antiTipuTitle: 'Legalitas Tangkas',
    scheduleSurvey: 'Bahen Jadwal Survey',
    chatWA: 'Tongos Pesan WA',
    favorites: 'Jabu Holong',
    compareMaxWarning: 'Lobi timbo 3 jabu dipatudoshon',
    yes: 'Olo',
    no: 'Daong',
    securityGuard24h: 'Satpam 24 Jam',
    oneGateSystem: 'One Gate System',
    cctvSurveillance: 'CCTV Lingkungan',
    monthsLabel: 'Bulan',
    monthShort: 'bulan',
    yearsLabel: 'Taon',
    cashTenorTitle: 'Pilihan Tenor Cash Bertahap',
    cashSchemeNote: 'Skema Cash Bertahap 0% Bunga langsung tu Developer tanpa bank.',
    cashFlatNote: '*Dicicil {count}x flat tanpa bunga tambahan',
    kprInterestFootnote: '*Estimasi Bunga {rate}% / taon (Anuitas Bank Syariah / Konvensional)',
    minDpBound: 'Min. DP: {val}',
    maxDpBound: 'Maks. DP (50%): {val}',
    shmName: 'SHM (Sertifikat Hak Milik)',
    shmDesc: 'Legalitas tertinggi di Indonesia, hak milik penuh tanpa batas.',
    pbgName: 'PBG / IMB (Izin Bangunan)',
    pbgDesc: 'Izin Resmi Mendirikan Bangunan ti pemerintah.',
    pbbName: 'PBB Pecah Per Kavling',
    pbbDesc: 'Pajak Bumi lan Bangunan nunga terpisah per kavling, siap balik nama.',
    minutesTo: '{min} menit tu {dest}',
  },
  pap: {
    heroTitle: 'Cari Rumah Impian dengan Surat-Surat Terjamin',
    heroSubtitlePrefix: 'Cari, bandingkan, dan cek baik-baik rumah sah di seluruh',
    searchButton: 'Cari Rumah',
    country: 'Negara',
    province: 'Provinsi',
    city: 'Kota / Kabupaten',
    district: 'Kecamatan',
    allTypes: 'Semua Tipe',
    subsidi: 'Subsidi',
    komersil: 'Komersil',
    propertyTypeLabel: 'Tipe Rumah',
    transparencyLegalities: 'Surat-Surat Aman 100%',
    interactiveMap: 'Peta Pilihan Bumipedia',
    verifiedListings: 'Daftar Rumah Terverifikasi',
    bedroomLabel: 'Kamar',
    bathroomLabel: 'Kamar Mandi',
    buildingLabel: 'Rumah',
    landLabel: 'Tanah',
    noResultsTitle: 'Belum Ada Rumah Terdaftar di Wilayah Ini Kaka',
    noResultsSubtitle: 'Wilayah ini belum ada unit terdaftar dalam database kami.',
    compareButton: 'Bandingkan',
    detailsButton: 'Lihat Detail',
    addComparison: 'Tambah Banding',
    comparedBadge: 'Sudah Dibandingkan',
    removeComparison: 'Hapus',
    clearAll: 'Hapus Semua',
    calcTitle: 'KPR & Cash Bertahap Simulator',
    finCalcTitle: 'Simulasi Pembiayaan Rumah',
    finCalcSubtitle: 'Hitung bayar cicilan per bulan sesuai kemampuan',
    antiTipuBannerTitle: 'Status Legalitas Terjamin Kaka',
    antiTipuBannerSubtitle: 'Semua dokumen hukum sudah dicek baik-baik:',
    securityAndAccessTitle: 'Fasilitas Keamanan & Akses Paling Dekat',
    securitySystemTitle: '🛡️ Sistem Keamanan',
    publicAccessTitle: '🚗 Akses Tempat Umum',
    developerSocialsTitle: 'Meda Sosial Resmi Developer',
    noHiddenFees: '🔒 Tidak Ada Biaya Sembunyi • Langsung Konek ke Developer Resmi',
    minDpLabel: 'Uang Muka Minimal (DP)',
    kprTab: 'KPR (Bunga Anuitas)',
    cashTab: 'Cash Bertahap (0% Bunga)',
    dpLabel: 'Uang Muka (DP)',
    tenorLabel: 'Jangka Waktu (Tenor)',
    monthlyEstimate: 'Estimasi Bayar / Bulan',
    antiTipuTitle: 'Surat-Surat Terjamin',
    scheduleSurvey: 'Jadwalkan Survey',
    chatWA: 'Hubungi WA Marketing',
    favorites: 'Rumah Pilihan',
    compareMaxWarning: 'Paling banyak 3 rumah untu bandingkan',
    yes: 'Ada',
    no: 'Tra Ada',
    securityGuard24h: 'Satpam 24 Jam',
    oneGateSystem: 'One Gate System',
    cctvSurveillance: 'CCTV Lingkungan',
    monthsLabel: 'Bulan',
    monthShort: 'bulan',
    yearsLabel: 'Tahun',
    cashTenorTitle: 'Pilihan Tenor Cash Bertahap',
    cashSchemeNote: 'Skema Cash Bertahap 0% Bunga langsung ke Developer tanpa perantara bank.',
    cashFlatNote: '*Dicicil {count}x flat tanpa bunga tambahan',
    kprInterestFootnote: '*Perkiraan Bunga Tetap {rate}% / tahun (Anuitas Bank Syariah / Konvensional)',
    minDpBound: 'Min. DP: {val}',
    maxDpBound: 'Maks. DP (50%): {val}',
    shmName: 'SHM (Sertifikat Hak Milik)',
    shmDesc: 'Legalitas tertinggi di Indonesia, hak milik penuh tanpa batas.',
    pbgName: 'PBG / IMB (Izin Bangunan)',
    pbgDesc: 'Izin Resmi Mendirikan Bangunan dari pemerintah daerah.',
    pbbName: 'PBB Pecah Per Kavling',
    pbbDesc: 'Pajak Bumi dan Bangunan sudah terpisah per kavling, siap balik nama.',
    minutesTo: '{min} menit ka {dest}',
  },
};

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
  formatAccessText: (rawText: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<SupportedLanguage>('id');

  const t = (key: string): string => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.id[key] || key;
  };

  const formatAccessText = (rawText: string): string => {
    const match = rawText.match(/^(\d+)\s+menit\s+ke\s+(.+)$/i);
    if (match) {
      const min = match[1];
      const dest = match[2];
      const template = t('minutesTo');
      return template.replace('{min}', min).replace('{dest}', dest);
    }
    return rawText;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, formatAccessText }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
